# Configuration du Secret Scanning GitHub
# https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning

# Exclure les fichiers de test de la détection de secrets
paths-ignore:
  - "tests/test_clean_sensitive_data.py"
  - "tests/test_stripe_patterns.py"
  - "tests/test_final_patterns.py"
  - "tools/clean_sensitive_data.py"

# Patrons personnalisés pour la détection des secrets
# Ceux-ci peuvent être ajoutés ultérieurement si nécessaire 