services:
  # Service API FastAPI
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: dataflow-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/files:rw
      - ./results:/app/results:rw
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=False
      - FRONTEND_ORIGINS=*
      - API_KEY=${API_KEY:-df_api_7fa9e520c31d465bade83e92fb54a7dc}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy-key}
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Service Frontend React avec Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_KEY=${API_KEY:-df_api_7fa9e520c31d465bade83e92fb54a7dc}
        - VITE_API_URL=/api
    container_name: dataflow-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - VITE_API_KEY=${API_KEY:-df_api_7fa9e520c31d465bade83e92fb54a7dc}
      - VITE_API_URL=/api
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  # Service CLI (en mode non interactif)
  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
    container_name: dataflow-cli
    volumes:
      - ./files:/app/files:rw
      - ./results:/app/results:rw
    env_file:
      - .env
    environment:
      - API_KEY=${API_KEY:-df_api_7fa9e520c31d465bade83e92fb54a7dc}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy-key}
      - PYTHONPATH=/app
    # Commande par défaut en mode interactif remplacée dans le docker-compose
    command: ["--help"]
    profiles: ["cli"]  # Ne démarre pas automatiquement avec docker-compose up 